name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  release-windows:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ELECTRON_BUILDER_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Configure npm
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set fetch-retries 5
          npm config set fetch-retry-maxtimeout 120000
          npm cache clean --force
      - name: Install deps (retry with mirror fallback)
        shell: bash
        run: |
          set -e
          for i in 1 2 3; do
            if npm install --no-fund --no-audit; then
              exit 0
            fi
            echo "npm install attempt ${i} failed; retrying..."
            sleep 5
          done
          echo "primary registry failed; switching to mirror"
          npm config set registry https://registry.npmmirror.com
          npm cache clean --force
          npm install --no-fund --no-audit
      - name: Build renderer
        run: npm run build
      - name: Build and publish
        run: npx --yes electron-builder --publish always