name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release-windows:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci --no-fund --no-audit

      - name: Build renderer
        run: npm run build

      - name: Build and publish
        run: npx --yes electron-builder --publish always